import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

/*
 * Providers
 * */
import { ModalProvider } from "@/components/GlobalUI/Providers/ModalProvider";

const inter = Inter({
  subsets: ["latin"], // You can add other subsets if needed
  variable: "--font-inter", // Optional, to use with CSS variables
  weight: ["400", "600", "700"], // Optional: specify weights as needed
});

export const metadata: Metadata = {
  title: "iFrame",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased bg-appPrimaryBackground`}
      >
        <ModalProvider />
        {children}
      </body>
    </html>
  );
}
