import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

/*
 * Providers
 * */
import { ModalProvider } from "@/components/GlobalUI/Providers/ModalProvider";

/*
 * UI Components
 * */
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "iFrame",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased bg-appPrimaryBackground`}
      >
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Montserrat:wght@400;700&family=Open+Sans:wght@400;700&family=Raleway:wght@400;700&family=Roboto:wght@400;700&family=Pixelify+Sans:wght@400;700&display=swap"
          rel="stylesheet"
        />
        <ModalProvider />
        <Toaster position="top-center" />
        {children}
        <div style={{ fontFamily: "Open Sans" }}>&nbsp;</div>
        <div style={{ fontFamily: "Roboto" }}>&nbsp;</div>
        <div style={{ fontFamily: "Pixelify Sans" }}>&nbsp;</div>
        <div style={{ fontFamily: "Lato" }}>&nbsp;</div>
        <div style={{ fontFamily: "Montserrat" }}>&nbsp;</div>
        <div style={{ fontFamily: "Raleway" }}>&nbsp;</div>
      </body>
    </html>
  );
}
